### ISSUE TITLE
Typo in sempy_labs.report.clone_report()

### ISSUE THREAD

**Issue by patryksitarek** [microsoft/semantic-link-labs#119]
**Describe the bug**
I found a bug in the sempy_labs.report.clone_report method. When defining all parameters, I get an exception KeyError: 'Dataset Id'.
The error message is pointing to src/sempy_labs/report/_report_functions.py file, line 475 "target_dataset_id = dfD_filt["Dataset Id"].iloc[0]".

Probably it's just a typo. A few lines above, the fabric.list_reports() method is called, which contains the 'Dataset ID' column, instead of 'Dataset Id'.

**To Reproduce**
1. Call sempy_labs.report.clone_report() method with all args determined.
2. See error

**Expected behavior**
Report to be cloned.

**Environment**
 - Microsoft Fabric notebook
 - Microsoft Edge browser

**Comment by m-kovalsky** [comment]
Thanks for reporting. I have a pending PR to improve this function which resolves this issue as well.
________________________________
From: Patryk Sitarek ***@***.***>
Sent: Tuesday, September 3, 2024 4:50:05 PM
To: microsoft/semantic-link-labs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/semantic-link-labs] Typo in sempy_labs.report.clone_report() (Issue #119)


Describe the bug
I found a bug in the sempy_labs.report.clone_report method. When defining all parameters, I get an exception KeyError: 'Dataset Id'.
The error message is pointing to src/sempy_labs/report/_report_functions.py file, line 475 "target_dataset_id = dfD_filt["Dataset Id"].iloc[0]".

Probably it's just a typo. A few lines above, the fabric.list_reports() method is called, which contains the 'Dataset ID' column, instead of 'Dataset Id'.

To Reproduce
Steps to reproduce the behavior:

  1.  Call sempy_labs.report.clone_report() method with all args determined.
  2.  See error

Expected behavior
Report to be cloned.

Environment

  *   Microsoft Fabric notebook
  *   Microsoft Edge browser

**Comment by m-kovalsky** [comment]
Fixed in [0.7.3](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.3).
