### ISSUE TITLE
warehouse_connection - DDL Queries?

### ISSUE THREAD

**Issue by joshrodgersKA** [microsoft/semantic-link-labs#133]
I'm trying out the new warehouse_connection function. When running a DDL query, it seems to hang and never complete. The same query when ran in the Warehouse UI works instantly. If this is an issue with the Warehouse rather than the semantic-link package - let me  know and I'll open a ticket with support instead.

Thanks! 

![image](https://github.com/user-attachments/assets/775a4a78-e391-4955-b7ed-ebac7c8d259b)

Here's some sample code that I cannot get to work.

```
warehouse_connection = sempy_labs.ConnectWarehouse("Oracle_Silver")
sql = """
CREATE TABLE test_table (
    id INT ,
    name VARCHAR(255)
)
"""
warehouse_connection.query(sql)
```

**Comment by m-kovalsky** [comment]
Would you try using the syntax shown in this notebook:

https://github.com/microsoft/semantic-link-labs/blob/main/notebooks/Warehouse.ipynb
________________________________
From: Josh-Rodgers ***@***.***>
Sent: Thursday, September 12, 2024 5:23:13 AM
To: microsoft/semantic-link-labs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/semantic-link-labs] warehouse_connection - DDL Queries? (Issue #133)


I'm trying out the new warehouse_connection function. When running a DDL query, it seems to hang and never complete. The same query when ran in the Warehouse UI works instantly. If this is an issue with the Warehouse rather than the semantic-link package - let me know and I'll open a ticket with support instead.

Thanks!

image.png (view on web)<https://github.com/user-attachments/assets/775a4a78-e391-4955-b7ed-ebac7c8d259b>

Here's some sample code that I cannot get to work.

warehouse_connection = sempy_labs.ConnectWarehouse("Oracle_Silver")
sql = """
CREATE TABLE test_table (
    id INT ,
    name VARCHAR(255)
)
"""
warehouse_connection.query(sql)

**Comment by joshrodgersKA** [comment]
Tried this:

```
warehouse_name = "Oracle_Silver"
workspace_name = "KDW-Dev"
with sempy_labs.ConnectWarehouse(warehouse=warehouse_name, workspace=workspace_name) as sql:
    df = sql.query("CREATE TABLE dbo.test_table1 (id INT, name VARCHAR(255))")
```

Got the below error: 

---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
Cell In[31], line 4
      2 workspace_name = "KDW-Dev"
      3 with sempy_labs.ConnectWarehouse(warehouse=warehouse_name, workspace=workspace_name) as sql:
----> 4     df = sql.query("CREATE TABLE dbo.test_table1 (id INT, name VARCHAR(255))")

File /nfs4/pyenv-a53311db-30d3-4f33-b0b1-8d07ecea675d/lib/python3.10/site-packages/sempy/_utils/_log.py:273, in mds_log.<locals>.get_wrapper.<locals>.log_decorator_wrapper(*args, **kwargs)
    270     raise
    272 try:
--> 273     result = func(*args, **kwargs)
    275     # The invocation for get_message_dict moves after the function
    276     # so it can access the state after the method call
    277     message.update(extractor.get_completion_message_dict(result, arg_dict))

File /nfs4/pyenv-a53311db-30d3-4f33-b0b1-8d07ecea675d/lib/python3.10/site-packages/sempy_labs/_sql.py:83, in ConnectWarehouse.query(self, sql)
     79     cursor = self.connection.cursor()
     80     cursor.execute(sql)
     82     return pd.DataFrame.from_records(
---> 83         cursor.fetchall(), columns=[col[0] for col in cursor.description]
     84     )
     85 finally:
     86     if cursor:

ProgrammingError: No results.  Previous SQL was not a query.

**Comment by m-kovalsky** [comment]
Can you try running a SQL query and not a T-SQL query?
________________________________

**Comment by joshrodgersKA** [comment]
Do you mean like a select query? Those works fine. It seems that DDL doesn't want to work.

________________________________
From: m-kovalsky ***@***.***>
Sent: Wednesday, September 11, 2024 9:29:54 PM
To: microsoft/semantic-link-labs ***@***.***>
Cc: Rodgers, Josh ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/semantic-link-labs] warehouse_connection - DDL Queries? (Issue #133)


Can you try running a SQL query and not a T-SQL query?
________________________________

**Comment by m-kovalsky** [comment]
Currently, this function doesn't support T-SQL. Will look at adding this functionality.

**Comment by m-kovalsky** [comment]
Made a [PR](https://github.com/microsoft/semantic-link-labs/pull/148) for enabling this function to work for both SQL & T-SQL (and support multiple T-SQL queries provided in a list).

**Comment by m-kovalsky** [comment]
Updated in [0.7.4](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.4).
