### ISSUE TITLE
Semantic-Link-Labs library | schema enabled Lakehouse | Unsupported operation for schema enabled Lakehouse

### ISSUE THREAD

**Issue by somarine** [microsoft/semantic-link-labs#206]
Using Semantic-Link-Labs library in dataset migration with Microsoft Fabric schema enabled Lakehouse we get the message Unsupported operation for schema enabled Lakehouse.

I would like to if will be supported and if yes when

![Image](https://github.com/user-attachments/assets/59352de6-4129-4c41-8954-ebd05c076477)

**Comment by m-kovalsky** [comment]
See #173 for the answer

**Comment by knlsarda13** [comment]
Hey @m-kovalsky,
Referring to See https://github.com/microsoft/semantic-link-labs/issues/173
Is there any fix to staging results to a schema based lake house?
Example:
If I want to execute **sll.delta_analyzer('modelbparesults')** or similar delta tables for my Lake house it doesn't allow. Any work around or if it would be fixed in future?
