### ISSUE TITLE
A minor typo in the notebooks/Semantic Model Refresh.ipynb

### ISSUE THREAD

**Issue by Oddjobe** [microsoft/semantic-link-labs#239]
**Describe the bug**
A typo in the Refresh specific partitions section 
Parttions misspelled
 

**To Reproduce**
Go to section **Refresh specific partitions section** in the notebook Semantic Model Refresh.ipynb

labs.refresh_semantic_model(dataset=dataset, workspace=workspace, **parttions**=["'Sales'[Sales FY20]", "'Sales'[Sales FY21]"])

Should be:
labs.refresh_semantic_model(dataset=dataset, workspace=workspace, **partitions**=["'Sales'[Sales FY20]", "'Sales'[Sales FY21]"])

**Expected behavior**
labs.refresh_semantic_model(dataset=dataset, workspace=workspace, **partitions**=["'Sales'[Sales FY20]", "'Sales'[Sales FY21]"])

**Screenshots**
Runtime
![Image](https://github.com/user-attachments/assets/dc85835e-d964-4c8f-9bef-41135d3e29af)

**Comment by m-kovalsky** [comment]
This was literally just fixed a few seconds ago! Thanks Lamin!
________________________________
From: Lamin Jobe ***@***.***>
Sent: Wednesday, October 30, 2024 10:21:06 AM
To: microsoft/semantic-link-labs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/semantic-link-labs] A minor typo in the notebooks/Semantic Model Refresh.ipynb (Issue #239)


Describe the bug
A typo in the Refresh specific partitions section
Parttions misspelled

To Reproduce
Go to section Refresh specific partitions section in the notebook Semantic Model Refresh.ipynb

labs.refresh_semantic_model(dataset=dataset, workspace=workspace, parttions=["'Sales'[Sales FY20]", "'Sales'[Sales FY21]"])

Should be:
labs.refresh_semantic_model(dataset=dataset, workspace=workspace, partitions=["'Sales'[Sales FY20]", "'Sales'[Sales FY21]"])

Expected behavior
labs.refresh_semantic_model(dataset=dataset, workspace=workspace, partitions=["'Sales'[Sales FY20]", "'Sales'[Sales FY21]"])

Screenshots
Runtime
If applicable, add screenshots to help explain your problem.
image.png (view on web)<https://github.com/user-attachments/assets/dc85835e-d964-4c8f-9bef-41135d3e29af>

**Comment by Oddjobe** [comment]
No worries happy to help, Anders found another typo in the notebooks/Model Optimization.ipynb
"Visualize the contents of an exported Vertipaq **Analzyer** .zip file." should say **Analyzer**

![Image](https://github.com/user-attachments/assets/2b7c2c0d-e76e-4ecd-808d-791b97a81be9)

**Comment by m-kovalsky** [comment]
Thanks. Will be fixed in the next release.

**Comment by m-kovalsky** [comment]
Fixed in [0.8.4](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.4).
