### ISSUE TITLE
Add users to workspaces via their GraphId

### ISSUE THREAD

**Issue by sp-ics-mf** [microsoft/semantic-link-labs#304]
**Is your feature request related to a problem? Please describe.**
Currently, it is only possible to add workspace users via an email address. (https://github.com/microsoft/semantic-link-labs/blob/38afa97946a84d657ccb05a982484e359932e8c4/src/sempy_labs/_workspaces.py#L142)
I need to add security groups that are not mail-enabled to workspaces.

**Describe the solution you'd like**
The underlying REST API call allows for adding users by their GraphId, but this is only available to admin APIs. 
(https://learn.microsoft.com/en-gb/rest/api/power-bi/groups/add-group-user#request-body)
Ideally, a function in the sempy_labs.admin subpackage would support this.

Many thanks for your efforts!

**Comment by m-kovalsky** [comment]
Have you tried entering the Id (instead of the email address) into the email_address parameter? Generally, email_address is much more convenient which is why I used that as the function parameter name. Technically, the API behind this function wants the Id (as you would like) but it turns out that it also accepts the email address.

**Comment by sp-ics-mf** [comment]
Many thanks, that worked. As a suggestion, maybe would be worth to add this information in the documentation somewhere.

**Comment by m-kovalsky** [comment]
Added this to the docs (for the next release).

email_address : str
        The email address of the user. Also accepts the user identifier.
