### ISSUE TITLE
Unable to add a table to the default semantic model

### ISSUE THREAD

**Issue by blaine12100** [microsoft/semantic-link-labs#52]
**Describe the bug**
In the code snippets given here [Semantic Model TOM](https://github.com/microsoft/semantic-link-labs/blob/main/notebooks/Tabular%20Object%20Model.ipynb) I am able to connect to the default semantic model but I am unable to add a table to the semantic model.

**To Reproduce**
1. Create a table in the lakehouse
2. Create a new notebook
3. Use code defined above to add a table to the semantic model

**Expected behavior**
The table should get added to the semantic model.

**Screenshots**

![Error Image](https://github.com/user-attachments/assets/b205e59d-1d2f-4e77-8cdd-ddf1f05c6f34).

**Additional context**
I have admin access to this workspace and the lakehouse and notebooks have been created in a brand new workspace.

**Comment by m-kovalsky** [comment]
XMLA operations (such as TOM) are not allowed on the default semantic model. I recommend not using the default semantic model as it has a plethora of limitations.
________________________________
From: Dhruv Marwha ***@***.***>
Sent: Monday, July 29, 2024 5:09:01 PM
To: microsoft/semantic-link-labs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/semantic-link-labs] Unable to add a table to the default semantic model (Issue #52)


Describe the bug
In the code snippets given here Semantic Model TOM<https://github.com/microsoft/semantic-link-labs/blob/main/notebooks/Tabular%20Object%20Model.ipynb> I am able to connect to the default semantic model but I am unable to add a table to the semantic model.

To Reproduce
Steps to reproduce the behavior:

  1.  Create a table in the lakehouse
  2.  Create a new notebook
  3.  Use code defined above to add a table to the semantic model
  4.  See error

Expected behavior
The table should get added to the semantic model.

Screenshots

image.png (view on web)<https://github.com/user-attachments/assets/b205e59d-1d2f-4e77-8cdd-ddf1f05c6f34>.

Additional context
I have admin access to this workspace and the lakehouse and notebooks have been created in a brand new workspace.

**Comment by blaine12100** [comment]
I was not aware of this. Then I need to create a new semantic model and perform these operations on that correct? I believe I can create a semantic model from the sempy_labs sub package.

**Comment by m-kovalsky** [comment]
Correct. You can also create a semantic model for the web UI (lakehouse) or from power bi desktop, tabular editor etc.
________________________________

**Comment by blaine12100** [comment]
Since I'm focused on automation so will choose to create this from the sempy_labs package. After it's created I need to use the same process described in the notebook to connect to the new semantic model and add the necessary bits to it by using the TOM pacakge.

**Comment by m-kovalsky** [comment]
Yes, you can use the create_blank_semantic_model function to create the initial model and then use the tom package to add all the elements (expression, tables, partitions, columns, measures etc.).
________________________________

**Comment by blaine12100** [comment]
Thank you for helping me in solving this issue. Closing the issue. In case of future issues, do I create new issues?

**Comment by m-kovalsky** [comment]
Yes, please create a new issue for each item of feedback which you have - bug, question, feature request etc. Thank you.
________________________________
