### ISSUE TITLE
refresh_semantic_model to support max_parallelism parameter

### ISSUE THREAD

**Issue by gbrueckl** [microsoft/semantic-link-labs#66]
currently the `refresh_semantic_model` function does not support a `max_parallelism` parameter - would be great if this could be added as otherwise you need to fall back to the underlying refresh_dataset function and build the rest manually

another option would be to allow a generic payload parameter which would be passed to the underlying API call. if other named parameters exist, those could overwrite the values within the payload parameter

**Comment by m-kovalsky** [comment]
Ah you are correct. I’ll add that parameter in for the next release. Thanks for letting me know.
________________________________
From: Gerhard Brueckl ***@***.***>
Sent: Wednesday, August 7, 2024 1:29:36 PM
To: microsoft/semantic-link-labs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/semantic-link-labs] refresh_semantic_model to support max_parallelism parameter (Issue #66)


currently the refresh_semantic_model function does not support a max_parallelism parameter - would be great if this could be added as otherwise you need to fall back to the underlying refresh_dataset function and build the rest manually

another option would be to allow a generic payload parameter which would be passed to the underlying API call. if other named parameters exist, those could overwrite the values within the payload parameter

**Comment by m-kovalsky** [comment]
This is resolved in [0.7.0](https://github.com/microsoft/semantic-link-labs/releases/tag/0.7.0).

**Comment by gbrueckl** [comment]
awesome, thanks!
